### PR TITLE
add July 2019 meeting notes

### PR DESCRIPTION
**Pull request by kedusi**

### CODE REVIEW

**Comment by kedusi** [comment]
simple add of july notes

**Review by kedusi — COMMENTED** [review]
LGTM

**Comment by kedusi** [comment]
I thought I was working in my fork of the site. I'm still trying to learn github and this is my first pull request. However, if I've done anything right and all looks good, I do want to merge these changes. Cool?

**Comment by Kaytal** [comment]
The actual Markdown looks good.  Later today after work I'll pull this locally and build to validate it runs correctly.

**Pull request merged**
